steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zantara-rag-backend:v2.3-final', '-f', 'Dockerfile', '.']
    
  # Step 2: Push to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zantara-rag-backend:v2.3-final']

images:
  - 'gcr.io/$PROJECT_ID/zantara-rag-backend:v2.3-final'

timeout: 1200s

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
