[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install torch>=2.0.0 --index-url https://download.pytorch.org/whl/cpu",
    "pip install -r requirements.txt",
    "python -c 'from sentence_transformers import SentenceTransformer; SentenceTransformer(\"all-MiniLM-L6-v2\")'"
]

[start]
cmd = "uvicorn app.main_cloud:app --host 0.0.0.0 --port $PORT"
