[build]
# Use Dockerfile for build
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 180  # 3 minutes (allow time for ChromaDB download + model loading)
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Resource allocation
numReplicas = 1
