[build]
# Use Nixpacks for build (simpler than Dockerfile)
builder = "nixpacks"
nixpacksConfigPath = "./nixpacks.toml"
watchPaths = ["./**"]

[deploy]
# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 180  # 3 minutes (allow time for ChromaDB download + model loading)
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Resource allocation
numReplicas = 1
