# Cloud CDN Configuration for Zantara Bridge
apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-config
data:
  # CDN Configuration
  project_id: "involuted-box-469105-r0"
  region: "asia-southeast2"
  bucket_name: "zantara-static-assets-cdn"
  
---
# CDN Backend Configuration
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendBucket
metadata:
  name: zantara-static-backend
spec:
  projectRef:
    external: "involuted-box-469105-r0"
  bucketName: "zantara-static-assets-cdn"
  enableCdn: true
  cdnPolicy:
    cacheMode: "CACHE_ALL_STATIC"
    defaultTtl: 3600  # 1 hour
    maxTtl: 86400     # 24 hours
    clientTtl: 3600   # 1 hour
    negativeCaching: true
    negativeCachingPolicy:
      - code: 404
        ttl: 300  # 5 minutes
      - code: 410
        ttl: 300  # 5 minutes
    cacheKeyPolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
    compressionMode: "AUTOMATIC"

---
# URL Map for CDN
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeURLMap
metadata:
  name: zantara-cdn-urlmap
spec:
  projectRef:
    external: "involuted-box-469105-r0"
  defaultService:
    backendBucketRef:
      name: "zantara-static-backend"
  pathMatcher:
    - name: "static-matcher"
      defaultService:
        backendBucketRef:
          name: "zantara-static-backend"
      pathRule:
        - path: ["/static/*", "/assets/*", "/images/*", "/js/*", "/css/*"]
          service:
            backendBucketRef:
              name: "zantara-static-backend"
        - path: ["/api/*", "/health", "/metrics"]
          service:
            backendServiceRef:
              name: "zantara-cloud-run-backend"

---
# HTTPS Target Proxy
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHTTPSProxy
metadata:
  name: zantara-cdn-proxy
spec:
  projectRef:
    external: "involuted-box-469105-r0"
  urlMapRef:
    name: "zantara-cdn-urlmap"
  sslCertificateRefs:
    - name: "zantara-ssl-cert"

---
# Global Forwarding Rule
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeGlobalForwardingRule
metadata:
  name: zantara-cdn-forwarding-rule
spec:
  projectRef:
    external: "involuted-box-469105-r0"
  target:
    targetHTTPSProxyRef:
      name: "zantara-cdn-proxy"
  portRange: "443"
  ipAddress:
    addressRef:
      name: "zantara-static-ip"

---
# Security Policy
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  name: zantara-cdn-security-policy
spec:
  projectRef:
    external: "involuted-box-469105-r0"
  rule:
    - action: "allow"
      priority: 1000
      match:
        versionedExpr: "SRC_IPS_V1"
        config:
          srcIpRanges: ["*"]
      description: "Allow all by default"
    - action: "deny(403)"
      priority: 2000
      match:
        expr:
          expression: "origin.region_code == 'CN' || origin.region_code == 'RU'"
      description: "Block certain regions"
    - action: "rate_based_ban"
      priority: 3000
      match:
        versionedExpr: "SRC_IPS_V1"
        config:
          srcIpRanges: ["*"]
      rateLimitOptions:
        rateLimitThreshold:
          count: 100
          intervalSec: 60
        banThreshold:
          count: 500
          intervalSec: 600
        banDurationSec: 3600
      description: "Rate limiting and DDoS protection"