[build]
# Use Dockerfile for build (at repo root with correct paths)
builder = "dockerfile"
dockerfilePath = "Dockerfile.rag"
watchPaths = ["apps/backend-rag 2/backend/**", "Dockerfile.rag"]

[deploy]
# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 180  # 3 minutes (allow time for ChromaDB download + model loading)
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Resource allocation
numReplicas = 1
