# Railway Configuration - RAG BACKEND ONLY
[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/backend-rag/backend/Dockerfile"

[deploy]
startCommand = "python migrations/001_fix_missing_tables.py && uvicorn app.main_cloud:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
