[build]
# Use Dockerfile for build (at repo root with correct paths)
builder = "dockerfile"
dockerfilePath = "Dockerfile.rag"
watchPaths = ["apps/backend-rag 2/backend/**", "Dockerfile.rag"]

[deploy]
# No HTTP healthcheck configured - Railway will monitor container process
# App takes 30-40s to start (ChromaDB download + model loading)
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Resource allocation
numReplicas = 1
