# Railway Configuration - FORCE DOCKERFILE USAGE
# This file forces Railway to use Dockerfile instead of NIXPACKS

[build]
# Force Railway to use Dockerfile
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Use Railway's automatic port detection
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
