[build]
# Use nixpacks with Node.js detection
builder = "nixpacks"
# Just build - npm i happens in Nixpacks install phase
buildCommand = "npm run build"

[deploy]
# Start command
startCommand = "npm start"

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Resource allocation
numReplicas = 1
