[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python migrations/001_fix_missing_tables.py"
]

[start]
cmd = "uvicorn app.main_cloud:app --host 0.0.0.0 --port $PORT"
