[build]
# Use Nixpacks for automatic Python build
builder = "NIXPACKS"
watchPaths = ["./**"]

[deploy]
# Explicitly use main_cloud.py (not main_integrated.py)
startCommand = "uvicorn app.main_cloud:app --host 0.0.0.0 --port $PORT"

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 600  # 10 minutes (ChromaDB download 72MB + model loading takes time)
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Resource allocation
numReplicas = 1