[build]
# Use Dockerfile for production build
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPaths = ["./**"]

[deploy]
# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 600  # 10 minutes (ChromaDB download 72MB + model loading takes time)
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Resource allocation
numReplicas = 1