"""
NUZANTARA PRIME - Identity Module Data Layer
SQLModel models mapping to existing Node.js backend tables
"""

from datetime import datetime

from sqlalchemy import Column
from sqlmodel import Field, Relationship, SQLModel


class User(SQLModel, table=True):
    """
    User model mapping to existing team_members table

    IMPORTANT: This maps to the EXISTING table created by Node.js backend.
    We use table_name="team_members" to connect to the same table.
    """

    __tablename__ = "team_members"

    # Primary key - Node.js uses VARCHAR(36), not UUID type
    # Note: Database uses gen_random_uuid() as default, but we accept string IDs
    id: str = Field(
        primary_key=True,
        max_length=36,
        description="User ID (UUID as VARCHAR, generated by database)",
    )

    # User identification
    # Map Python 'name' to database 'full_name' column
    name: str = Field(
        sa_column=Column("full_name", nullable=False), max_length=255, description="Full name"
    )
    email: str = Field(
        unique=True, index=True, max_length=255, description="Email address (unique)"
    )

    # Authentication
    pin_hash: str = Field(max_length=255, description="bcrypt hashed PIN/password")

    # User attributes
    role: str = Field(
        default="member", max_length=100, description="User role (e.g., 'admin', 'member', 'CEO')"
    )
    department: str | None = Field(default=None, max_length=100, description="Department name")
    language: str = Field(default="en", max_length=10, description="Preferred language code")

    # Status flags
    personalized_response: bool = Field(
        default=False, description="Enable personalized AI responses"
    )
    # Map Python 'is_active' to database 'active' column
    is_active: bool = Field(
        sa_column=Column("active", default=True), default=True, description="Account active status"
    )

    # Notes/Metadata for AI understanding
    notes: str | None = Field(
        default=None, description="Character notes and personality traits for AI"
    )

    # Security tracking
    last_login: datetime | None = Field(default=None, description="Last successful login timestamp")
    failed_attempts: int = Field(default=0, description="Number of failed login attempts")
    locked_until: datetime | None = Field(default=None, description="Account lock expiry timestamp")

    # Timestamps
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="Account creation timestamp"
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow, description="Last update timestamp"
    )

    # Relationships
    sessions: list["UserSession"] = Relationship(back_populates="user")


class UserSession(SQLModel, table=True):
    """
    User Session model mapping to existing user_sessions table

    IMPORTANT: This maps to the EXISTING table created by Node.js backend.
    The primary key is 'id' (VARCHAR), not 'session_id'.
    """

    __tablename__ = "user_sessions"

    # Primary key - Node.js uses VARCHAR(255) for session ID
    id: str = Field(primary_key=True, max_length=255, description="Session ID (primary key)")

    # Foreign key to team_members
    user_id: str = Field(
        foreign_key="team_members.id", max_length=36, description="User ID reference"
    )

    # Session metadata
    email: str = Field(max_length=255, description="User email (denormalized for quick access)")

    # Timestamps
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="Session creation timestamp"
    )
    last_accessed: datetime = Field(
        default_factory=datetime.utcnow, description="Last access timestamp"
    )
    expires_at: datetime = Field(description="Session expiration timestamp")

    # Request metadata
    ip_address: str | None = Field(default=None, description="Client IP address")
    user_agent: str | None = Field(default=None, description="Client user agent string")

    # Status
    is_active: bool = Field(default=True, description="Session active status")

    # Relationships
    user: User | None = Relationship(back_populates="sessions")
