# NUZANTARA-RAILWAY Configuration Guide
# 
# Railway uses Dockerfile instead of railway.toml when both are present.
# All railway.toml files have been removed to use Docker-only deployment.

# SERVICE CONFIGURATION:
# 
# 1. TypeScript Backend (ts-backend-production-568d)
#    - Root Directory: apps/backend-ts
#    - Dockerfile: apps/backend-ts/Dockerfile
#    - URL: https://ts-backend-production-568d.up.railway.app
#
# 2. RAG Backend (scintillating-kindness-production-47e3)  
#    - Root Directory: apps/backend-rag/backend
#    - Dockerfile: apps/backend-rag/backend/Dockerfile
#    - URL: https://scintillating-kindness-production-47e3.up.railway.app
#
# 3. Frontend Webapp
#    - Static files served from apps/webapp/
#    - No separate Railway service needed
#
# DEPLOYMENT STATUS:
# ✅ All railway.toml files removed
# ✅ Dockerfile for TypeScript backend created
# ✅ Dockerfile for RAG backend exists and optimized
# ✅ Services use Docker-only deployment
