# NUZANTARA-RAILWAY Configuration Guide
# 
# This file provides configuration guidance for the monorepo deployment.
# The main railway.toml is in the root directory.

# SERVICE CONFIGURATION:
# 
# 1. TypeScript Backend (ts-backend-production-568d)
#    - Root Directory: apps/backend-ts
#    - Config File: apps/backend-ts/railway.toml
#    - URL: https://ts-backend-production-568d.up.railway.app
#
# 2. RAG Backend (scintillating-kindness-production-47e3)  
#    - Root Directory: apps/backend-rag/backend
#    - Config File: apps/backend-rag/backend/railway.toml
#    - URL: https://scintillating-kindness-production-47e3.up.railway.app
#
# 3. Frontend Webapp
#    - Static files served from apps/webapp/
#    - No separate Railway service needed
#
# DEPLOYMENT STATUS:
# ✅ Main railway.toml created in root
# ✅ Backend-specific configs exist
# ✅ Services should auto-deploy on git push


