# Cloudflare Pages configuration for Bali Zero Publication

name = "balizero-publication"
compatibility_date = "2025-01-15"

# Build configuration
[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# Pages configuration
[[pages]]
name = "balizero-publication"
routes = [
  "insights.balizero.com/*",
  "balizero-publication.pages.dev/*"
]

# Custom domain (configure in Cloudflare dashboard)
# insights.balizero.com
