openapi: 3.1.0
info:
  title: ZANTARA API - Direct Endpoints
  description: Bali Zero Business Services API
  version: 5.2.0
servers:
  - url: https://zantara-v520-chatgpt-patch-1064094238013.europe-west1.run.app
    description: Production server

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

paths:
  /health:
    get:
      operationId: checkHealth
      summary: Check API health
      security: []
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  version:
                    type: string

  /contact.info:
    get:
      operationId: getContactInfo
      summary: Get Bali Zero contact information
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Contact information retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  company:
                    type: string
                  services:
                    type: array
                    items:
                      type: string
                  communication:
                    type: object
                    properties:
                      email:
                        type: string
                      whatsapp:
                        type: string

  /lead.save:
    post:
      operationId: saveLead
      summary: Save a new lead
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - service
              properties:
                name:
                  type: string
                  description: Lead name
                email:
                  type: string
                  description: Lead email
                service:
                  type: string
                  description: Service type
                details:
                  type: string
                  description: Additional details
                nationality:
                  type: string
                  description: Lead nationality
                urgency:
                  type: string
                  enum: [normal, urgent, immediate]
      responses:
        '200':
          description: Lead saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  leadId:
                    type: string
                  followUpScheduled:
                    type: boolean

  /identity.resolve:
    post:
      operationId: resolveUserIdentity
      summary: Resolve user identity
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Identity resolved
          content:
            application/json:
              schema:
                type: object

  /ai.chat:
    post:
      operationId: chatWithAI
      summary: Chat with AI assistant
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - prompt
              properties:
                prompt:
                  type: string
                  description: User message
                model:
                  type: string
                  description: AI model to use
                  default: auto
      responses:
        '200':
          description: AI response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                  model:
                    type: string

  /metrics:
    get:
      operationId: getSystemMetrics
      summary: Get system metrics
      security: []
      responses:
        '200':
          description: System metrics
          content:
            application/json:
              schema:
                type: object

  /docs:
    get:
      operationId: getAPIDocs
      summary: Get API documentation
      security: []
      responses:
        '200':
          description: API documentation
          content:
            text/html:
              schema:
                type: string

  /call:
    post:
      operationId: callHandler
      summary: Call a specific handler
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - key
                - params
              properties:
                key:
                  type: string
                  description: Handler key to call
                  enum:
                    # Business Core Handlers
                    - contact.info
                    - lead.save
                    - quote.generate
                    - document.prepare

                    # Identity & Team Management
                    - identity.resolve
                    - onboarding.start
                    - onboarding.ambaradam.start
                    - team.list
                    - team.get
                    - team.departments

                    # AI Chat Handlers
                    - ai.chat
                    - openai.chat
                    - claude.chat
                    - gemini.chat
                    - cohere.chat

                    # ZANTARA Intelligence
                    - oracle.simulate
                    - oracle.analyze
                    - oracle.predict
                    - assistant.route

                    # Google Workspace (requires OAuth2)
                    - sheets.create
                    - sheets.read
                    - sheets.append
                    - drive.upload
                    - drive.list
                    - docs.create
                    - calendar.create

                    # Memory System
                    - memory.save
                    - memory.get
                    - memory.list
                    - memory.search

                    # Collaboration
                    - slack.notify
                params:
                  type: object
                  description: Handler parameters (varies by handler key)
                  properties:
                    # Business Handlers
                    service:
                      type: string
                      description: Service type (for quote.generate - visa, company, tax, real-estate)
                    details:
                      type: string
                      description: Additional details for quote or lead
                    name:
                      type: string
                      description: Lead name (for lead.save)
                    email:
                      type: string
                      description: Email address (for lead.save, identity.resolve)
                    nationality:
                      type: string
                      description: Nationality (for lead.save)
                    urgency:
                      type: string
                      enum: [normal, urgent, immediate]
                      description: Urgency level (for lead.save)

                    # AI Chat
                    prompt:
                      type: string
                      description: Chat prompt (for ai.chat, openai.chat, etc.)
                    model:
                      type: string
                      description: AI model to use (auto, gpt-4, claude-3, gemini-pro)
                    conversation_id:
                      type: string
                      description: Conversation ID for context

                    # Team Management
                    userId:
                      type: string
                      description: User ID (for team.get, memory operations)
                    department:
                      type: string
                      description: Department filter (for team.list)

                    # Memory System
                    key:
                      type: string
                      description: Memory key (for memory.save/get)
                    content:
                      type: string
                      description: Content to save (for memory.save)
                    query:
                      type: string
                      description: Search query (for memory.search)

                    # Google Workspace
                    title:
                      type: string
                      description: Title (for sheets.create, docs.create)
                    data:
                      type: array
                      description: Initial data for spreadsheet
                      items:
                        type: array
                        items:
                          type: string
                    spreadsheetId:
                      type: string
                      description: Spreadsheet ID (for sheets operations)
                    range:
                      type: string
                      description: Range in A1 notation
                    values:
                      type: array
                      description: Data to append
                      items:
                        type: array
                        items:
                          type: string
                    fileName:
                      type: string
                      description: Name of the file (for drive.upload)
                    mimeType:
                      type: string
                      description: MIME type of file (for drive.upload)
                    media:
                      type: object
                      description: File content (for drive.upload)
                      properties:
                        body:
                          type: string
                          description: Base64 encoded file content
                    calendarId:
                      type: string
                      description: Calendar ID (for calendar.create) - use "primary" for default or specific ID for other calendars
                      default: primary
                    event:
                      type: object
                      description: Calendar event details (for calendar.create)
                      properties:
                        summary:
                          type: string
                          description: Event title
                        description:
                          type: string
                          description: Event description
                        start:
                          type: object
                          properties:
                            dateTime:
                              type: string
                              description: ISO 8601 datetime
                            timeZone:
                              type: string
                        end:
                          type: object
                          properties:
                            dateTime:
                              type: string
                              description: ISO 8601 datetime
                            timeZone:
                              type: string
                        attendees:
                          type: array
                          items:
                            type: object
                            properties:
                              email:
                                type: string
      responses:
        '200':
          description: Handler executed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  data:
                    type: object
                    properties:
                      spreadsheetId:
                        type: string
                        description: ID of created spreadsheet (sheets.create)
                      url:
                        type: string
                        description: URL to edit the spreadsheet (sheets.create)
                      values:
                        type: array
                        description: Data read from spreadsheet (sheets.read)
                        items:
                          type: array
                      update:
                        type: object
                        description: Update information (sheets.append)
                        properties:
                          updatedRange:
                            type: string
                          updatedRows:
                            type: number
                          updatedCells:
                            type: number
                      file:
                        type: object
                        description: Uploaded file information (drive.upload)
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          webViewLink:
                            type: string
                      event:
                        type: object
                        description: Created calendar event (calendar.create)
                        properties:
                          id:
                            type: string
                          htmlLink:
                            type: string
                          status:
                            type: string