[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements-worker.txt"
]

# Start command disabled - run manually instead
# Manual command: python3 scripts/llama_nightly_worker.py --days 3 --max-golden 50 --regenerate-cultural
[start]
cmd = "echo 'LLAMA Nightly Worker: Run manually (see README for command)' && sleep infinity"
