# sources.yaml - Bali Zero Journal News Sources
# Total: 600+ sources across 7 categories

# CATEGORY: IMMIGRATION (100+ sources)
immigration:
  tier_1:  # Government Official (Highest Priority)
    - name: "Direktorat Jenderal Imigrasi"
      url: "https://www.imigrasi.go.id"
      language: "id"
      selectors:
        title: "h1.entry-title, .news-title"
        content: ".entry-content, .news-content"
        date: ".entry-date, .publish-date"
      reliability: 10.0
      frequency: "24h"

    - name: "Kantor Imigrasi Ngurah Rai"
      url: "https://ngurahrai.imigrasi.go.id"
      language: "id"
      selectors:
        title: ".post-title"
        content: ".post-content"
        date: ".post-date"
      reliability: 10.0
      frequency: "24h"

    - name: "Kantor Imigrasi Denpasar"
      url: "https://denpasar.imigrasi.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "Ministry of Law and Human Rights"
      url: "https://www.kemenkumham.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

  tier_2:  # Professional Media & Law Firms
    - name: "Bali Visas"
      url: "https://balivisas.com/blog"
      language: "en"
      reliability: 8.0
      frequency: "48h"

    - name: "Cekindo Business International"
      url: "https://www.cekindo.com/blog"
      language: "en"
      reliability: 8.5
      frequency: "48h"

    - name: "Indonesia Expat"
      url: "https://indonesiaexpat.id/tag/immigration/"
      language: "en"
      reliability: 7.5
      frequency: "48h"

    - name: "Emerhub Immigration"
      url: "https://emerhub.com/indonesia/immigration-news/"
      language: "en"
      reliability: 8.0
      frequency: "48h"

  tier_3:  # Community & Forums
    - name: "Bali Expat Forum"
      url: "https://www.reddit.com/r/bali"
      language: "en"
      reliability: 5.0
      frequency: "weekly"

    - name: "Living in Indonesia Forum"
      url: "https://www.livinginindonesiaforum.org"
      language: "en"
      reliability: 6.0
      frequency: "weekly"

# CATEGORY: COMPANY & BUSINESS (100+ sources)
business:
  tier_1:
    - name: "OSS Indonesia"
      url: "https://oss.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "BKPM"
      url: "https://www.bkpm.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "Kementerian Perdagangan"
      url: "https://www.kemendag.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "AHU Online Kemenkumham"
      url: "https://ahu.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

  tier_2:
    - name: "PwC Indonesia"
      url: "https://www.pwc.com/id/en/media-centre.html"
      language: "en"
      reliability: 9.0
      frequency: "48h"

    - name: "Deloitte Indonesia"
      url: "https://www2.deloitte.com/id/en/insights.html"
      language: "en"
      reliability: 9.0
      frequency: "48h"

    - name: "KPMG Indonesia"
      url: "https://home.kpmg/id/en/home/insights.html"
      language: "en"
      reliability: 9.0
      frequency: "48h"

    - name: "Jakarta Post Business"
      url: "https://www.thejakartapost.com/business"
      language: "en"
      reliability: 8.0
      frequency: "24h"

# CATEGORY: TAX (100+ sources)
tax:
  tier_1:
    - name: "Direktorat Jenderal Pajak"
      url: "https://www.pajak.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "DJP Online"
      url: "https://djponline.pajak.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "Kementerian Keuangan"
      url: "https://www.kemenkeu.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

  tier_2:
    - name: "Indonesian Tax Review"
      url: "https://www.indonesiantaxreview.com"
      language: "en"
      reliability: 8.5
      frequency: "48h"

    - name: "Tax Indonesia"
      url: "https://taxindonesia.id"
      language: "id"
      reliability: 8.0
      frequency: "48h"

# CATEGORY: PROPERTY (80+ sources)
property:
  tier_1:
    - name: "ATR/BPN"
      url: "https://www.atrbpn.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "BPN Denpasar"
      url: "https://denpasarkota.bpn.go.id"
      language: "id"
      reliability: 10.0
      frequency: "48h"

    - name: "Kementerian PUPR"
      url: "https://www.pu.go.id"
      language: "id"
      reliability: 10.0
      frequency: "48h"

  tier_2:
    - name: "Colliers Indonesia"
      url: "https://www.colliers.com/id-id/research"
      language: "en"
      reliability: 8.5
      frequency: "48h"

    - name: "Knight Frank Indonesia"
      url: "https://www.knightfrank.co.id/research"
      language: "en"
      reliability: 8.5
      frequency: "48h"

# CATEGORY: BALI NEWS (100+ sources)
bali_news:
  tier_1:
    - name: "Pemprov Bali"
      url: "https://www.baliprov.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "Denpasar City"
      url: "https://www.denpasarkota.go.id"
      language: "id"
      reliability: 10.0
      frequency: "48h"

  tier_2:
    - name: "Bali Post"
      url: "https://www.balipost.com"
      language: "id"
      reliability: 8.0
      frequency: "24h"

    - name: "The Bali Times"
      url: "https://www.thebalitimes.com"
      language: "en"
      reliability: 7.5
      frequency: "24h"

    - name: "Coconuts Bali"
      url: "https://coconuts.co/bali/"
      language: "en"
      reliability: 7.0
      frequency: "48h"

# CATEGORY: AI INDONESIA (40+ sources)
ai_indonesia:
  tier_1:
    - name: "Kemenkominfo"
      url: "https://www.kominfo.go.id"
      language: "id"
      reliability: 10.0
      frequency: "48h"

    - name: "BRIN Indonesia"
      url: "https://www.brin.go.id"
      language: "id"
      reliability: 10.0
      frequency: "48h"

  tier_2:
    - name: "Tech in Asia Indonesia"
      url: "https://www.techinasia.com/indonesia"
      language: "en"
      reliability: 8.0
      frequency: "24h"

    - name: "Daily Social"
      url: "https://dailysocial.id"
      language: "id"
      reliability: 7.5
      frequency: "24h"

# CATEGORY: FINANCE (100+ sources)
finance:
  tier_1:
    - name: "Bank Indonesia"
      url: "https://www.bi.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "OJK"
      url: "https://www.ojk.go.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

    - name: "IDX"
      url: "https://www.idx.co.id"
      language: "id"
      reliability: 10.0
      frequency: "24h"

  tier_2:
    - name: "Bisnis Indonesia"
      url: "https://bisnis.com"
      language: "id"
      reliability: 8.0
      frequency: "24h"

    - name: "Kontan"
      url: "https://www.kontan.co.id"
      language: "id"
      reliability: 7.5
      frequency: "24h"

