name: Deploy RAG Backend (AMD64)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker Image (AMD64)
        run: |
          cd "apps/backend-rag 2/backend"
          docker build \
            --no-cache \
            --platform linux/amd64 \
            -t gcr.io/involuted-box-469105-r0/zantara-rag-backend:${{ github.sha }} \
            -t gcr.io/involuted-box-469105-r0/zantara-rag-backend:latest \
            .

      - name: Push to Google Container Registry
        run: |
          docker push gcr.io/involuted-box-469105-r0/zantara-rag-backend:${{ github.sha }}
          docker push gcr.io/involuted-box-469105-r0/zantara-rag-backend:latest

      - name: Deploy to Cloud Run
        run: |
          # First: Deploy with new image and clear old config
          gcloud run deploy zantara-rag-backend \
            --image gcr.io/involuted-box-469105-r0/zantara-rag-backend:${{ github.sha }} \
            --region europe-west1 \
            --port 8000 \
            --memory 2Gi \
            --cpu 2 \
            --min-instances 0 \
            --max-instances 3 \
            --concurrency 80 \
            --cpu-throttling \
            --no-cpu-boost \
            --allow-unauthenticated \
            --clear-env-vars \
            --clear-secrets \
            --no-traffic

          # Second: Update with new environment configuration
          gcloud run services update zantara-rag-backend \
            --region europe-west1 \
            --update-secrets="ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,API_KEYS_INTERNAL=API_KEYS_INTERNAL:latest,RUNPOD_API_KEY=RUNPOD_API_KEY:latest,HF_API_KEY=HF_API_KEY:latest" \
            --set-env-vars="TYPESCRIPT_BACKEND_URL=https://zantara-v520-nuzantara-himaadsxua-ew.a.run.app,RUNPOD_LLAMA_ENDPOINT=https://api.runpod.ai/v2/itz2q5gmid4cyt/runsync,ENABLE_RERANKER=false"

          # Third: Route traffic to latest revision
          gcloud run services update-traffic zantara-rag-backend \
            --region europe-west1 \
            --to-latest

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 30
          curl -f https://zantara-rag-backend-1064094238013.europe-west1.run.app/health || exit 1
          echo "✅ RAG Backend deployed successfully with QUADRUPLE-AI + Tool Use"
