name: gitops-validate
on: [pull_request]
jobs:
  kustomize-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          kustomize build k8s/overlays/prod > /tmp/out.yaml
          kubectl apply --dry-run=client -f /tmp/out.yaml
